name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #build-unix:

    #runs-on: ${{ matrix.os }}
    #strategy:
      #matrix:
        #os: [ubuntu-latest, macos-latest, macos-10.15, ubuntu-18.04]

    #steps:
    #- uses: actions/checkout@v2
    #- name: Checkout submodules
      #uses: snickerbockers/submodules-init@v4
    #- name: test
      #run: mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../ && make -j4 && ./packtest
      
  build-win:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: snickerbockers/submodules-init@v4
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: tests
      run: cmake --build build --config Debug && ls
    - name: run_tests
      run: cd build && ./Debug/packtest.exe
